CREATE TABLE artists (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    sort_name TEXT,
    album_count BIGINT NOT NULL DEFAULT 0,
    cover_art_hash TEXT,
    song_count BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_artists_name ON artists (LOWER(name));
CREATE INDEX idx_artists_sort_name ON artists (LOWER(sort_name));

CREATE TABLE albums (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    artist_id TEXT NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
    year INTEGER,
    genre TEXT,
    song_count BIGINT NOT NULL DEFAULT 0,
    duration BIGINT NOT NULL DEFAULT 0,
    cover_art_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cover_art_width INTEGER,
    cover_art_height INTEGER
);

CREATE INDEX idx_albums_artist ON albums(artist_id);
CREATE INDEX idx_albums_name ON albums (LOWER(name));
CREATE INDEX idx_albums_year ON albums(year);
CREATE INDEX idx_albums_genre ON albums(genre);

CREATE TABLE songs (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    album_id TEXT REFERENCES albums(id) ON DELETE SET NULL,
    artist_id TEXT NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
    music_folder_id BIGINT REFERENCES music_folders(id) ON DELETE CASCADE,
    track_number INTEGER,
    disc_number INTEGER NOT NULL DEFAULT 1,
    year INTEGER,
    genre TEXT,
    duration BIGINT NOT NULL DEFAULT 0,
    bitrate INTEGER,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    file_format TEXT NOT NULL,
    file_mtime BIGINT,
    partial_hash TEXT,
    full_file_hash TEXT,
    cover_art_hash TEXT,
    marked_for_deletion_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cover_art_width INTEGER,
    cover_art_height INTEGER,
    original_replaygain_track_gain DOUBLE PRECISION,
    original_replaygain_track_peak DOUBLE PRECISION,
    computed_replaygain_track_gain DOUBLE PRECISION,
    computed_replaygain_track_peak DOUBLE PRECISION,
    UNIQUE(file_path, music_folder_id)
);

CREATE INDEX idx_songs_album ON songs(album_id);
CREATE INDEX idx_songs_artist ON songs(artist_id);
CREATE INDEX idx_songs_title ON songs (LOWER(title));
CREATE INDEX idx_songs_music_folder ON songs(music_folder_id);

CREATE TABLE scrobbles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    song_id TEXT NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
    played_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    submission BOOLEAN NOT NULL DEFAULT TRUE,
    play_count BIGINT NOT NULL DEFAULT 1,
    description TEXT,
    queue_source_type TEXT,
    queue_source_id TEXT
);

CREATE INDEX idx_scrobbles_user_time ON scrobbles(user_id, played_at DESC);
CREATE INDEX idx_scrobbles_song ON scrobbles(song_id);

CREATE TABLE starred (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL CHECK(item_type IN ('song', 'album', 'artist')),
    item_id TEXT NOT NULL,
    starred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, item_type, item_id)
);

CREATE INDEX idx_starred_user ON starred(user_id);
CREATE INDEX idx_starred_item ON starred(item_type, item_id);

CREATE TABLE ratings (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL CHECK(item_type IN ('song', 'album', 'artist')),
    item_id TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK(rating >= 1 AND rating <= 5),
    rated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, item_type, item_id)
);

CREATE INDEX idx_ratings_user ON ratings(user_id);
CREATE INDEX idx_ratings_item ON ratings(item_type, item_id);