CREATE TABLE IF NOT EXISTS match_dictionary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    lookup_key TEXT NOT NULL,
    original_title TEXT,
    original_artist TEXT,
    original_album TEXT,
    original_duration_ms INTEGER,
    song_id TEXT NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, lookup_key)
);

CREATE INDEX IF NOT EXISTS idx_match_dictionary_user_key ON match_dictionary(user_id, lookup_key);
