//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "albums")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub artist_id: String,
    pub year: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub genre: Option<String>,
    pub song_count: i64,
    pub duration: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_art_hash: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub cover_art_width: Option<i32>,
    pub cover_art_height: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artists::Entity",
        from = "Column::ArtistId",
        to = "super::artists::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Artists,
    #[sea_orm(has_many = "super::songs::Entity")]
    Songs,
}

impl Related<super::artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artists.def()
    }
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Songs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
