//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod albums;
pub mod api_keys;
pub mod artists;
pub mod cover_art_thumbnails;
pub mod disabled_songs;
pub mod listening_sessions;
pub mod match_dictionary;
pub mod music_folders;
pub mod play_queue_entries;
pub mod play_queues;
pub mod playback_sessions;
pub mod playlist_folders;
pub mod playlist_shares;
pub mod playlist_songs;
pub mod playlists;
pub mod ratings;
pub mod scrobbles;
pub mod server_config;
pub mod shuffle_excludes;
pub mod smart_playlists;
pub mod songs;
pub mod starred;
pub mod tagger_pending_edits;
pub mod tagger_scripts;
pub mod tagger_session_tracks;
pub mod tagger_sessions;
pub mod user_library_access;
pub mod user_playlist_overrides;
pub mod user_preferences;
pub mod users;
