//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "music_folders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub path: String,
    pub enabled: bool,
    pub watch_enabled: bool,
    pub last_scanned_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub scan_error: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::songs::Entity")]
    Songs,
    #[sea_orm(has_many = "super::user_library_access::Entity")]
    UserLibraryAccess,
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Songs.def()
    }
}

impl Related<super::user_library_access::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLibraryAccess.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_library_access::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::user_library_access::Relation::MusicFolders
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
