//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "play_queues")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i64,
    #[sea_orm(column_type = "Text")]
    pub source_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_name: Option<String>,
    pub current_index: i64,
    pub position_ms: i64,
    pub is_shuffled: bool,
    pub shuffle_seed: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shuffle_indices_json: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub repeat_mode: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub filters_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sort_json: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub changed_by: String,
    pub total_count: Option<i64>,
    pub is_lazy: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub song_ids_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub instance_id: Option<String>,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub session_id: String,
    pub version: i64,
    #[sea_orm(column_type = "Text")]
    pub source_api: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
