//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "playlists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub comment: Option<String>,
    pub owner_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub folder_id: Option<String>,
    pub is_public: bool,
    pub song_count: i64,
    pub duration: i64,
    pub position: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub last_played_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::playlist_folders::Entity",
        from = "Column::FolderId",
        to = "super::playlist_folders::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    PlaylistFolders,
    #[sea_orm(has_many = "super::playlist_shares::Entity")]
    PlaylistShares,
    #[sea_orm(has_many = "super::playlist_songs::Entity")]
    PlaylistSongs,
    #[sea_orm(has_many = "super::user_playlist_overrides::Entity")]
    UserPlaylistOverrides,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::playlist_folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistFolders.def()
    }
}

impl Related<super::playlist_shares::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistShares.def()
    }
}

impl Related<super::playlist_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistSongs.def()
    }
}

impl Related<super::user_playlist_overrides::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPlaylistOverrides.def()
    }
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        super::playlist_songs::Relation::Songs.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::playlist_songs::Relation::Playlists.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::playlist_shares::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::playlist_shares::Relation::Playlists.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
