//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "playlist_folders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_id: Option<String>,
    pub owner_id: i64,
    pub position: i64,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub cover_art: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::playlists::Entity")]
    Playlists,
    #[sea_orm(has_many = "super::smart_playlists::Entity")]
    SmartPlaylists,
    #[sea_orm(has_many = "super::user_playlist_overrides::Entity")]
    UserPlaylistOverrides,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Playlists.def()
    }
}

impl Related<super::smart_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SmartPlaylists.def()
    }
}

impl Related<super::user_playlist_overrides::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPlaylistOverrides.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
