//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "smart_playlists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub comment: Option<String>,
    pub owner_id: i64,
    pub is_public: bool,
    #[sea_orm(column_type = "Text")]
    pub rules_json: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub sort_field: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sort_direction: Option<String>,
    pub max_songs: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub folder_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub last_played_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::playlist_folders::Entity",
        from = "Column::FolderId",
        to = "super::playlist_folders::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    PlaylistFolders,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::playlist_folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistFolders.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
