//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "songs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub album_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub artist_id: String,
    pub music_folder_id: Option<i64>,
    pub track_number: Option<i32>,
    pub disc_number: i32,
    pub year: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub genre: Option<String>,
    pub duration: i64,
    pub bitrate: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub file_path: String,
    pub file_size: i64,
    #[sea_orm(column_type = "Text")]
    pub file_format: String,
    pub file_mtime: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub partial_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub full_file_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_art_hash: Option<String>,
    pub marked_for_deletion_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub cover_art_width: Option<i32>,
    pub cover_art_height: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub original_replaygain_track_gain: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub original_replaygain_track_peak: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub computed_replaygain_track_gain: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub computed_replaygain_track_peak: Option<f64>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub waveform_data: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub bliss_features: Option<Vec<u8>>,
    pub bliss_version: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::albums::Entity",
        from = "Column::AlbumId",
        to = "super::albums::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Albums,
    #[sea_orm(
        belongs_to = "super::artists::Entity",
        from = "Column::ArtistId",
        to = "super::artists::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Artists,
    #[sea_orm(has_many = "super::disabled_songs::Entity")]
    DisabledSongs,
    #[sea_orm(has_many = "super::listening_sessions::Entity")]
    ListeningSessions,
    #[sea_orm(has_many = "super::match_dictionary::Entity")]
    MatchDictionary,
    #[sea_orm(
        belongs_to = "super::music_folders::Entity",
        from = "Column::MusicFolderId",
        to = "super::music_folders::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MusicFolders,
    #[sea_orm(has_many = "super::play_queue_entries::Entity")]
    PlayQueueEntries,
    #[sea_orm(has_many = "super::playlist_songs::Entity")]
    PlaylistSongs,
    #[sea_orm(has_many = "super::scrobbles::Entity")]
    Scrobbles,
    #[sea_orm(has_many = "super::shuffle_excludes::Entity")]
    ShuffleExcludes,
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Albums.def()
    }
}

impl Related<super::artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artists.def()
    }
}

impl Related<super::disabled_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DisabledSongs.def()
    }
}

impl Related<super::listening_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ListeningSessions.def()
    }
}

impl Related<super::match_dictionary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchDictionary.def()
    }
}

impl Related<super::music_folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicFolders.def()
    }
}

impl Related<super::play_queue_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayQueueEntries.def()
    }
}

impl Related<super::playlist_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistSongs.def()
    }
}

impl Related<super::scrobbles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scrobbles.def()
    }
}

impl Related<super::shuffle_excludes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShuffleExcludes.def()
    }
}

impl Related<super::playlists::Entity> for Entity {
    fn to() -> RelationDef {
        super::playlist_songs::Relation::Playlists.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::playlist_songs::Relation::Songs.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
