//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tagger_pending_edits")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub session_id: i64,
    #[sea_orm(column_type = "Text")]
    pub track_id: String,
    #[sea_orm(column_type = "Text")]
    pub track_type: String,
    #[sea_orm(column_type = "Text")]
    pub edited_tags: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub computed_path: Option<String>,
    pub cover_art_removed: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_art_filename: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub replacement_audio_filename: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub replacement_audio_original_name: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tagger_sessions::Entity",
        from = "Column::SessionId",
        to = "super::tagger_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TaggerSessions,
}

impl Related<super::tagger_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaggerSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
