//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tagger_sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub user_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub active_rename_script_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub active_tag_script_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub target_library_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub visible_columns: String,
    #[sea_orm(column_type = "Text")]
    pub column_widths: String,
    pub file_column_width: i64,
    pub show_library_prefix: bool,
    pub show_computed_path: bool,
    pub details_panel_open: bool,
    #[sea_orm(column_type = "Text")]
    pub dangerous_char_mode: String,
    #[sea_orm(column_type = "Text")]
    pub dangerous_char_replacement: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tagger_pending_edits::Entity")]
    TaggerPendingEdits,
    #[sea_orm(has_many = "super::tagger_session_tracks::Entity")]
    TaggerSessionTracks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::tagger_pending_edits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaggerPendingEdits.def()
    }
}

impl Related<super::tagger_session_tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaggerSessionTracks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
