//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub subsonic_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    pub is_admin: bool,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub lastfm_api_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lastfm_api_secret: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lastfm_session_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lastfm_username: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::disabled_songs::Entity")]
    DisabledSongs,
    #[sea_orm(has_many = "super::listening_sessions::Entity")]
    ListeningSessions,
    #[sea_orm(has_many = "super::match_dictionary::Entity")]
    MatchDictionary,
    #[sea_orm(has_many = "super::play_queue_entries::Entity")]
    PlayQueueEntries,
    #[sea_orm(has_many = "super::play_queues::Entity")]
    PlayQueues,
    #[sea_orm(has_one = "super::playback_sessions::Entity")]
    PlaybackSessions,
    #[sea_orm(has_many = "super::playlist_folders::Entity")]
    PlaylistFolders,
    #[sea_orm(has_many = "super::playlist_shares::Entity")]
    PlaylistShares,
    #[sea_orm(has_many = "super::playlists::Entity")]
    Playlists,
    #[sea_orm(has_many = "super::ratings::Entity")]
    Ratings,
    #[sea_orm(has_many = "super::scrobbles::Entity")]
    Scrobbles,
    #[sea_orm(has_many = "super::shuffle_excludes::Entity")]
    ShuffleExcludes,
    #[sea_orm(has_many = "super::smart_playlists::Entity")]
    SmartPlaylists,
    #[sea_orm(has_many = "super::starred::Entity")]
    Starred,
    #[sea_orm(has_many = "super::tagger_scripts::Entity")]
    TaggerScripts,
    #[sea_orm(has_one = "super::tagger_sessions::Entity")]
    TaggerSessions,
    #[sea_orm(has_many = "super::user_library_access::Entity")]
    UserLibraryAccess,
    #[sea_orm(has_many = "super::user_playlist_overrides::Entity")]
    UserPlaylistOverrides,
    #[sea_orm(has_one = "super::user_preferences::Entity")]
    UserPreferences,
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::disabled_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DisabledSongs.def()
    }
}

impl Related<super::listening_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ListeningSessions.def()
    }
}

impl Related<super::match_dictionary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchDictionary.def()
    }
}

impl Related<super::play_queue_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayQueueEntries.def()
    }
}

impl Related<super::play_queues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayQueues.def()
    }
}

impl Related<super::playback_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaybackSessions.def()
    }
}

impl Related<super::playlist_folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistFolders.def()
    }
}

impl Related<super::playlist_shares::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistShares.def()
    }
}

impl Related<super::ratings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ratings.def()
    }
}

impl Related<super::scrobbles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scrobbles.def()
    }
}

impl Related<super::shuffle_excludes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShuffleExcludes.def()
    }
}

impl Related<super::smart_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SmartPlaylists.def()
    }
}

impl Related<super::starred::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Starred.def()
    }
}

impl Related<super::tagger_scripts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaggerScripts.def()
    }
}

impl Related<super::tagger_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaggerSessions.def()
    }
}

impl Related<super::user_library_access::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserLibraryAccess.def()
    }
}

impl Related<super::user_playlist_overrides::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPlaylistOverrides.def()
    }
}

impl Related<super::user_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPreferences.def()
    }
}

impl Related<super::music_folders::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_library_access::Relation::MusicFolders.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_library_access::Relation::Users.def().rev())
    }
}

impl Related<super::playlists::Entity> for Entity {
    fn to() -> RelationDef {
        super::playlist_shares::Relation::Playlists.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::playlist_shares::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
