#!/usr/bin/env bash
# Generate TypeScript bindings from Rust types using ts-rs
# Run from the project root directory

set -euo pipefail

# File ordering must not depend on the developer or CI machine's locale.
export LC_ALL=C

GENERATED_DIR="client/src/lib/api/generated"

echo "🔨 Generating TypeScript bindings..."

# Clean and recreate output directory to avoid stale files
rm -rf "$GENERATED_DIR"
mkdir -p "$GENERATED_DIR"

# Run library tests to trigger ts-rs exports without compiling unrelated test targets.
# The tests with #[ts(export)] will generate .ts files
cargo test --lib export_bindings

# Check if any .ts files were generated
if [ -z "$(find "$GENERATED_DIR" -maxdepth 1 -type f -name '*.ts' -print -quit)" ]; then
    echo "❌ No TypeScript files were generated"
    exit 1
fi

# Generate index.ts that re-exports all types
echo "📝 Generating index.ts..."
INDEX_FILE="$GENERATED_DIR/index.ts"

cat > "$INDEX_FILE" << 'EOF'
// Auto-generated by scripts/generate-ts-bindings.sh
// Do not edit manually - run 'moon run generate-bindings' to regenerate

EOF

# Add exports for each .ts file (except index.ts) in byte-stable order.
while IFS= read -r -d '' f; do
    filename=$(basename "$f")
    if [ "$filename" != "index.ts" ]; then
        name="${filename%.ts}"
        echo "export type { $name } from './$name';" >> "$INDEX_FILE"
    fi
done < <(find "$GENERATED_DIR" -maxdepth 1 -type f -name '*.ts' -print0 | sort -z)

if grep -R -n -w bigint "$GENERATED_DIR"; then
    echo "❌ Generated API contracts contain bigint; JSON integer fields must be annotated as TypeScript number"
    exit 1
fi

# Count generated types
TYPE_COUNT=$(find "$GENERATED_DIR" -maxdepth 1 -type f -name '*.ts' ! -name index.ts | wc -l)

echo "✅ Generated $TYPE_COUNT TypeScript types in $GENERATED_DIR"
