#!/bin/bash
# Generate TypeScript bindings from Rust types using ts-rs
# Run from the project root directory

set -e

GENERATED_DIR="client/src/lib/api/generated"

echo "🔨 Generating TypeScript bindings..."

# Clean and recreate output directory to avoid stale files
rm -rf "$GENERATED_DIR"
mkdir -p "$GENERATED_DIR"

# Run cargo test to trigger ts-rs exports
# The tests with #[ts(export)] will generate .ts files
cargo test export_bindings

# Check if any .ts files were generated
if [ -z "$(ls -A "$GENERATED_DIR"/*.ts 2>/dev/null)" ]; then
    echo "❌ No TypeScript files were generated"
    exit 1
fi

# Generate index.ts that re-exports all types
echo "📝 Generating index.ts..."
INDEX_FILE="$GENERATED_DIR/index.ts"

cat > "$INDEX_FILE" << 'EOF'
// Auto-generated by scripts/generate-ts-bindings.sh
// Do not edit manually - run 'moon run generate-bindings' to regenerate

EOF

# Add exports for each .ts file (except index.ts)
for f in "$GENERATED_DIR"/*.ts; do
    filename=$(basename "$f")
    if [ "$filename" != "index.ts" ]; then
        name="${filename%.ts}"
        echo "export type { $name } from './$name';" >> "$INDEX_FILE"
    fi
done

# Count generated types
TYPE_COUNT=$(ls -1 "$GENERATED_DIR"/*.ts 2>/dev/null | grep -v index.ts | wc -l)

echo "✅ Generated $TYPE_COUNT TypeScript types in $GENERATED_DIR"
