// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TopAlbum } from "./TopAlbum";
import type { TopArtist } from "./TopArtist";
import type { TopTrack } from "./TopTrack";

export type PeriodReview = {
  year: number;
  month: number | null;
  totalListeningSecs: bigint;
  totalPlayCount: bigint;
  uniqueTracks: bigint;
  uniqueAlbums: bigint;
  uniqueArtists: bigint;
  topArtists: Array<TopArtist>;
  topAlbums: Array<TopAlbum>;
  topTracks: Array<TopTrack>;
};
