// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopAlbum = { albumId: string, albumName: string, artistName: string | null, playCount: bigint, totalDurationSecs: bigint, coverArt: string | null, };
