// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopArtist = { artistId: string, artistName: string, playCount: bigint, totalDurationSecs: bigint, coverArt: string | null, };
