// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopTrack = {
  trackId: string;
  trackTitle: string;
  artistName: string | null;
  albumName: string | null;
  playCount: bigint;
  totalDurationSecs: bigint;
  coverArt: string | null;
};
